version: '3'

services:
  db:
    image: mysql

    container_name: mysql-brightme

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_DATABASE: any_db
      MYSQL_ROOT_PASSWORD: any_password_root

    ports:
      - '3306:3306'

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
