version: '3'

services:
  db:
    image: mysql

    container_name: mysql-brightme

    command: --default-authentication-plugin=mysql_native_password
    restart: always

    environment:
      MYSQL_DATABASE: ${DEV_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DEV_DB_ROOT_PASSWORD}

    ports:
      - 3308:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
